import { cpSync, rmSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import react from '@vitejs/plugin-react'
import tailwindcss from 'tailwindcss'
import loadConfig from 'tailwindcss/loadConfig'
import { defineConfig, type Plugin } from 'vite'

import capacitorConfig from '../../capacitor.config'

const root = resolve(__dirname, '../..')
const www = resolve(root, 'native/www')
// Loaded through Tailwind's own loader: the config require()s its plugins.
const tailwindConfig = loadConfig(resolve(root, 'tailwind.config.ts'))
const shim = (file: string) => resolve(__dirname, 'shims', file)

/**
 * Files next to the bundle that aren't imported code:
 * - app-url.js: `server.url` from capacitor.config.ts (CAP_SERVER_URL or
 *   production, plus /app), so "Try again" goes back to exactly the URL the
 *   shell was synced with. Capacitor opens any other URL in Safari.
 * - flags/ and geo/: the round components load `/flags/xx.svg` and
 *   `/geo/countries-110m.json` from the site's public/ folder. Copied to the
 *   same paths in native/www, so they load from disk offline.
 */
function offlineFiles(): Plugin {
  return {
    name: 'population-offline-files',
    apply: 'build',
    closeBundle() {
      const url = String(capacitorConfig.server?.url ?? '').replace(/\/$/, '')
      writeFileSync(
        resolve(www, 'app-url.js'),
        `// Generated by native/offline/vite.config.ts (npm run native:offline).\nwindow.APP_URL = ${JSON.stringify(url)}\n`,
      )
      for (const dir of ['flags', 'geo']) {
        rmSync(resolve(www, dir), { recursive: true, force: true })
        cpSync(resolve(root, 'public', dir), resolve(www, dir), { recursive: true })
      }
    },
  }
}

/**
 * The offline island (NATIVE.md): a practice round built into native/www, so
 * the app still plays with no connection. Run through `npm run native:offline`,
 * which `native:sync` and `native:dev` call before `cap sync`.
 */
export default defineConfig({
  root: __dirname,
  base: './',
  publicDir: false,
  plugins: [react(), offlineFiles()],
  resolve: {
    // Specific stand-ins first, then the tsconfig "@/*" alias.
    alias: [
      { find: 'next/link', replacement: shim('next-link.tsx') },
      { find: 'next/navigation', replacement: shim('next-navigation.ts') },
      { find: '@clerk/nextjs', replacement: shim('clerk.ts') },
      // deviceStorage reads the site's store from Preferences but never writes there.
      { find: /^@\/lib\/native$/, replacement: shim('native.ts') },
      // Network only. The stand-in exports nothing, so a new import fails the build.
      { find: /^posthog-js(\/.*)?$/, replacement: shim('blocked.ts') },
      { find: /^@supabase\/.*$/, replacement: shim('blocked.ts') },
      { find: /^@\/lib\/(supabase|stats)(\/.*)?$/, replacement: shim('blocked.ts') },
      { find: '@', replacement: root },
    ],
  },
  css: {
    postcss: {
      plugins: [
        tailwindcss({
          ...tailwindConfig,
          content: [...(tailwindConfig.content as string[]).map((g) => resolve(root, g)), resolve(__dirname, '*.tsx')],
        }),
      ],
    },
  },
  build: {
    outDir: www,
    emptyOutDir: false,
    assetsDir: 'offline-assets',
    rollupOptions: { input: resolve(__dirname, 'offline.html') },
    // The question bank alone is about two megabytes; it loads from disk, not the network.
    chunkSizeWarningLimit: 4000,
  },
})
