export const adjectives = [
  'zany',
  'quirky',
  'whimsical',
  'eccentric',
  'wacky',
  'kooky',
  'groovy',
  'far-out',
  'funky',
  'crazy',
  'madcap',
  'zesty',
  'zippy',
  'lively',
  'peppy',
  'sassy',
  'cheeky',
  'playful',
  'mischievous',
  'impish',
  'goofy',
  'silly',
  'hilarious',
  'comical',
  'jovial',
  'jocular',
  'mirthful',
  'rambunctious',
  'boisterous',
  'frolicsome',
  'rollicking',
  'jaunty',
  'sprightly',
  'vivacious',
  'spirited',
  'effervescent',
  'bubbly',
  'ebullient',
  'exuberant',
  'flamboyant',
  'flamboyant',
  'flashy',
  'dazzling',
  'glamorous',
  'swanky',
  'snazzy',
  'ritzy',
  'posh',
  'swish',
]

export const animals = [
  'aardvarks',
  'alligators',
  'alpacas',
  'ants',
  'antelopes',
  'armadillos',
  'baboons',
  'badgers',
  'bats',
  'bears',
  'beavers',
  'bees',
  'bison',
  'boars',
  'buffalo',
  'butterflies',
  'camels',
  'caribou',
  'cats',
  'caterpillars',
  'chameleons',
  'cheetahs',
  'chickens',
  'chimpanzees',
  'cobras',
  'cougars',
  'cows',
  'coyotes',
  'crabs',
  'crocodiles',
  'crows',
  'deer',
  'dogs',
  'dolphins',
  'donkeys',
  'doves',
  'dragonflies',
  'ducks',
  'eagles',
  'elephants',
  'elk',
  'falcons',
  'ferrets',
  'fish',
  'flamingos',
  'foxes',
  'frogs',
  'gazelles',
  'giraffes',
  'goats',
  'gorillas',
  'grasshoppers',
  'hamsters',
  'hedgehogs',
  'hippopotamuses',
  'horses',
  'hyenas',
  'iguanas',
  'jaguars',
  'jellyfish',
  'kangaroos',
  'koalas',
  'ladybugs',
  'lemurs',
  'leopards',
  'lions',
  'lizards',
  'lobsters',
  'lynxes',
  'moles',
  'monkeys',
  'moose',
  'mice',
  'octopuses',
  'ostriches',
  'otters',
  'owls',
  'pandas',
  'panthers',
  'parrots',
  'peacocks',
  'pelicans',
  'penguins',
  'pigs',
  'pigeons',
  'porcupines',
  'rabbits',
  'raccoons',
  'rats',
  'ravens',
  'rhinos',
  'salamanders',
  'seals',
  'sharks',
  'sheep',
  'skunks',
  'sloths',
  'snails',
  'snakes',
  'sparrows',
  'squids',
  'squirrels',
  'swans',
  'tigers',
  'toads',
  'turkeys',
  'turtles',
  'vultures',
  'walruses',
  'wasps',
  'whales',
  'wolves',
  'wombats',
  'zebras',
]

export const mockQuestions = [
  {
    id: 1,
    question: 'In what year did the fictional Battle of Eldoria take place?',
    answer: 1483,
    lower_bound: 1000,
    upper_bound: 2000,
  },
  {
    id: 2,
    question: 'How many moons does the imaginary planet Zog have?',
    answer: 5,
    lower_bound: 1,
    upper_bound: 10,
  },
  {
    id: 3,
    question: 'What is the maximum speed of a gryphon in the enchanted forest?',
    answer: 120,
    lower_bound: 50,
    upper_bound: 200,
  },
  {
    id: 4,
    question: 'How many rings of power were forged in the ancient city of Valoria?',
    answer: 13,
    lower_bound: 1,
    upper_bound: 20,
  },
  {
    id: 5,
    question: 'In what year was the mythical city of Atlantis founded?',
    answer: 3290,
    lower_bound: 2000,
    upper_bound: 4000,
  },
  {
    id: 6,
    question: 'How many species of dragons exist in the lore of Draconia?',
    answer: 7,
    lower_bound: 1,
    upper_bound: 10,
  },
  {
    id: 7,
    question: 'What is the population of the magical kingdom of Elvendale?',
    answer: 25000,
    lower_bound: 10000,
    upper_bound: 50000,
  },
  {
    id: 8,
    question: 'In what year did the Great Wizard Tournament occur?',
    answer: 1367,
    lower_bound: 1000,
    upper_bound: 1500,
  },
  {
    id: 9,
    question: 'How many ancient scrolls are hidden in the Temple of Secrets?',
    answer: 42,
    lower_bound: 20,
    upper_bound: 60,
  },
  {
    id: 10,
    question: 'What is the distance in leagues to the center of the enchanted realm?',
    answer: 300,
    lower_bound: 200,
    upper_bound: 400,
  },
  {
    id: 11,
    question: 'In what year did the legendary Battle of Ironforge take place?',
    answer: 1345,
    lower_bound: 1200,
    upper_bound: 1500,
  },
  {
    id: 12,
    question: 'How many towers are there in the mystical city of Eldoria?',
    answer: 9,
    lower_bound: 5,
    upper_bound: 15,
  },
  {
    id: 13,
    question: 'What is the average wingspan of a phoenix in meters?',
    answer: 7,
    lower_bound: 5,
    upper_bound: 10,
  },
  {
    id: 14,
    question: 'How many enchanted crystals are needed to power the Arcane Shield?',
    answer: 15,
    lower_bound: 10,
    upper_bound: 20,
  },
  {
    id: 15,
    question: 'In what year was the enchanted forest of Mystwood first discovered?',
    answer: 1120,
    lower_bound: 1000,
    upper_bound: 1300,
  },
  {
    id: 16,
    question: 'How many different species of magical plants are found in the Mystwood forest?',
    answer: 25,
    lower_bound: 20,
    upper_bound: 30,
  },
  {
    id: 17,
    question: 'What is the duration of the Great Lunar Eclipse in hours?',
    answer: 8,
    lower_bound: 6,
    upper_bound: 10,
  },
  {
    id: 18,
    question: 'How many magical artifacts are stored in the Grand Library of Arcadia?',
    answer: 150,
    lower_bound: 100,
    upper_bound: 200,
  },
  {
    id: 19,
    question: 'In what year did the first Dragon Festival take place in Draconia?',
    answer: 1450,
    lower_bound: 1400,
    upper_bound: 1500,
  },
  {
    id: 20,
    question: 'How many champions have won the Grand Wizard Tournament since its inception?',
    answer: 30,
    lower_bound: 20,
    upper_bound: 40,
  },
  {
    id: 21,
    question: 'What is the population of the underwater city of Aquapolis?',
    answer: 45000,
    lower_bound: 30000,
    upper_bound: 60000,
  },
  {
    id: 22,
    question: 'How many moons orbit the planet Thalassa?',
    answer: 4,
    lower_bound: 2,
    upper_bound: 6,
  },
  {
    id: 23,
    question: 'In what year did the Great Fire of Eldoria occur?',
    answer: 1583,
    lower_bound: 1500,
    upper_bound: 1600,
  },
  {
    id: 24,
    question: 'How many prophecies are inscribed in the ancient Scrolls of Time?',
    answer: 12,
    lower_bound: 10,
    upper_bound: 15,
  },
  {
    id: 25,
    question: 'What is the height of the tallest mountain in the Kingdom of Arkenia in meters?',
    answer: 3500,
    lower_bound: 3000,
    upper_bound: 4000,
  },
  {
    id: 26,
    question: 'How many knights are part of the Royal Guard of Elvendale?',
    answer: 50,
    lower_bound: 40,
    upper_bound: 60,
  },
  {
    id: 27,
    question: 'In what year did the first intergalactic council meeting take place?',
    answer: 2750,
    lower_bound: 2700,
    upper_bound: 2800,
  },
  {
    id: 28,
    question: 'How many planets are in the Galactic Federation?',
    answer: 15,
    lower_bound: 10,
    upper_bound: 20,
  },
  {
    id: 29,
    question: 'What is the speed of the fastest spaceship in the galaxy in light-years per hour?',
    answer: 3,
    lower_bound: 2,
    upper_bound: 5,
  },
  {
    id: 30,
    question: 'How many levels are there in the Tower of Mystics?',
    answer: 13,
    lower_bound: 10,
    upper_bound: 15,
  },
  {
    id: 31,
    question: 'In what year was the ancient city of Zaltara founded?',
    answer: 1023,
    lower_bound: 1000,
    upper_bound: 1100,
  },
  {
    id: 32,
    question: 'How many rings are there in the Circle of Power?',
    answer: 6,
    lower_bound: 5,
    upper_bound: 10,
  },
  {
    id: 33,
    question: 'What is the lifespan of an average elf in Elvendale in years?',
    answer: 300,
    lower_bound: 200,
    upper_bound: 400,
  },
  {
    id: 34,
    question: 'How many steps lead to the summit of the Great Pyramid of Azara?',
    answer: 500,
    lower_bound: 400,
    upper_bound: 600,
  },
  {
    id: 35,
    question: 'In what year did the first exploration of the Dark Abyss take place?',
    answer: 1834,
    lower_bound: 1800,
    upper_bound: 1900,
  },
  {
    id: 36,
    question: 'How many scrolls are kept in the Secret Archives of Eldoria?',
    answer: 80,
    lower_bound: 50,
    upper_bound: 100,
  },
  {
    id: 37,
    question: 'What is the distance in miles to the edge of the known universe?',
    answer: 1000000,
    lower_bound: 900000,
    upper_bound: 1100000,
  },
  {
    id: 38,
    question: 'How many guardian statues protect the entrance to the Crystal Cave?',
    answer: 12,
    lower_bound: 10,
    upper_bound: 15,
  },
  {
    id: 39,
    question: 'In what year was the first enchanted sword forged?',
    answer: 876,
    lower_bound: 800,
    upper_bound: 1000,
  },
  {
    id: 40,
    question: 'How many legendary beasts roam the land of Draconia?',
    answer: 7,
    lower_bound: 5,
    upper_bound: 10,
  },
]
